# Generated by Django 5.0.4 on 2024-05-17 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="blog/image",
                verbose_name="изображение",
            ),
        ),
    ]
