# Generated by Django 5.0.4 on 2024-05-18 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_blog_views_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="views_count",
            field=models.PositiveIntegerField(default=0, verbose_name="просмотры"),
        ),
    ]
